Set default value for end_time
Set default value CURRENT_TIMESTAMP for end_time column in migration log table otherwise it causes:

ERROR: SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'end_time'